import 'package:quokka/models/user_stats.dart';

class AchievementService {
  static List<Achievement> get allAchievements => [
        // Collector
        Achievement(
          id: 'collector_5',
          title: 'New Hobby',
          description: 'Own 5 games',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'collector_25',
          title: 'Shelf Filler',
          description: 'Own 25 games',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Collector',
        ),
        Achievement(
          id: 'collector_100',
          title: 'Museum Curator',
          description: 'Own 100 games',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Collector',
        ),
        Achievement(
          id: 'sold_1',
          title: 'Spring Cleaning',
          description: 'Sell your first game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'sold_5',
          title: 'Merchant',
          description: 'Sell 5 games',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Collector',
        ),
        Achievement(
          id: 'lend_1',
          title: 'Librarian',
          description: 'Lend a game to a friend',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'lend_10',
          title: 'Public Library',
          description: 'Lend games 10 times',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Collector',
        ),

        // Tactician
        Achievement(
          id: 'plays_10',
          title: 'Dice Roller',
          description: 'Log 10 play sessions',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Tactician',
        ),
        Achievement(
          id: 'plays_50',
          title: 'Regular Regular',
          description: 'Log 50 play sessions',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Tactician',
        ),
        Achievement(
          id: 'plays_100',
          title: 'Tabletop Legend',
          description: 'Log 100 play sessions',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Tactician',
        ),
        Achievement(
          id: 'session_long',
          title: 'Marathon',
          description: 'Log a session > 120 minutes',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Tactician',
        ),
        Achievement(
          id: 'session_short',
          title: 'Filler Fanatic',
          description: 'Log a session < 15 minutes',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Tactician',
        ),

        // Competitor
        Achievement(
          id: 'win_1',
          title: 'First Blood',
          description: 'Win a game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Competitor',
        ),
        Achievement(
          id: 'win_10',
          title: 'Champion',
          description: 'Win 10 games',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Competitor',
        ),
        Achievement(
          id: 'win_50',
          title: 'Unstoppable',
          description: 'Win 50 games',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Competitor',
        ),
        Achievement(
          id: 'players_5',
          title: 'Social Butterfly',
          description: 'Add 5 unique players',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Competitor',
        ),
        Achievement(
          id: 'distinct_10',
          title: 'Variety Show',
          description: 'Play 10 distinct games',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Competitor',
        ),

        // Wishlist
        Achievement(
          id: 'wish_1',
          title: 'Dreamer',
          description: 'Add a game to your wishlist',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Wishful Thinker',
        ),
        Achievement(
          id: 'wish_to_own_1',
          title: 'Deal Hunter',
          description: 'Move a game from Wishlist to Collection',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Wishful Thinker',
        ),
        
        // Expansionist
        Achievement(
          id: 'expansion_1',
          title: 'Expansion Starter',
          description: 'Own your first expansion',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Expansionist',
        ),
        Achievement(
          id: 'expansion_10',
          title: 'Big Box Collector',
          description: 'Own 10 expansions',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Expansionist',
        ),
        Achievement(
          id: 'expansion_30',
          title: 'Completionist',
          description: 'Own 30 expansions',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Expansionist',
        ),
        Achievement(
          id: 'expansion_play_1',
          title: 'Enhanced Experience',
          description: 'Play a game with at least 1 expansion',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Expansionist',
        ),
        Achievement(
          id: 'expansion_play_3',
          title: 'Content Overload',
          description: 'Play a session with 3 or more expansions',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Expansionist',
        ),
        Achievement(
          id: 'expansion_variety_5',
          title: 'Flavor Enhancer',
          description: 'Own expansions for 5 different base games',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Expansionist',
        ),
        
        // Complexity achievements
        Achievement(
          id: 'complexity_simplest',
          title: 'Gateway Gamer',
          description: 'Play your simplest game (lowest weight)',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Challenger',
        ),
        Achievement(
          id: 'complexity_hardest',
          title: 'Brain Burner',
          description: 'Play your most complex game (highest weight)',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Challenger',
        ),
        
        // Rating achievements
        Achievement(
          id: 'rating_lowest',
          title: 'Hidden Gem Hunter',
          description: 'Play your lowest rated game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Challenger',
        ),
        Achievement(
          id: 'rating_highest',
          title: 'Crowd Pleaser',
          description: 'Play your highest rated game',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Challenger',
        ),
        
        // Player count achievements
        Achievement(
          id: 'solo_player',
          title: 'Lone Wolf',
          description: 'Play a game solo',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Social',
        ),
        Achievement(
          id: 'max_players',
          title: 'Party Host',
          description: 'Play a game with its maximum player count (3+ players)',
          tier: AchievementTier.silver,
          xpReward: 40,
          category: 'The Social',
        ),
        
        // Purchase achievements
        Achievement(
          id: 'buy_new_game',
          title: 'Retail Therapy',
          description: 'Buy a brand new game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'buy_used_game',
          title: 'Thrift Shop Hero',
          description: 'Buy a used game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        
        // Player count ownership achievements
        Achievement(
          id: 'own_solo_game',
          title: 'Solo Adventurer',
          description: 'Own a solo-only game (1 player)',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'own_duo_game',
          title: 'Duelist',
          description: 'Own a 2-player only game',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        Achievement(
          id: 'own_party_game',
          title: 'Party Starter',
          description: 'Own a party game (8+ players)',
          tier: AchievementTier.bronze,
          xpReward: 20,
          category: 'The Collector',
        ),
        
        // Collection expansion achievements (20+ games required)
        Achievement(
          id: 'buy_new_best_rated',
          title: 'Raising the Bar',
          description: 'Buy a new highest-rated game (requires 20+ games)',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Collector',
        ),
        Achievement(
          id: 'buy_new_worst_rated',
          title: 'Guilty Pleasure',
          description: 'Buy a new lowest-rated game (requires 20+ games)',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Collector',
        ),
        Achievement(
          id: 'buy_new_most_complex',
          title: 'Complexity Conqueror',
          description: 'Buy a new most complex game (requires 20+ games)',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Collector',
        ),
        Achievement(
          id: 'buy_new_least_complex',
          title: 'Simplicity Seeker',
          description: 'Buy a new least complex game (requires 20+ games)',
          tier: AchievementTier.gold,
          xpReward: 80,
          category: 'The Collector',
        ),
      ];
}
